package com.bt.shopguide.dao.entity;

import java.io.Serializable;
import java.util.Date;

public class ContactInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTACT_INFO.id
     *
     * @mbggenerated Thu Oct 26 10:14:27 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTACT_INFO.name
     *
     * @mbggenerated Thu Oct 26 10:14:27 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTACT_INFO.email
     *
     * @mbggenerated Thu Oct 26 10:14:27 CST 2017
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTACT_INFO.phone
     *
     * @mbggenerated Thu Oct 26 10:14:27 CST 2017
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTACT_INFO.content
     *
     * @mbggenerated Thu Oct 26 10:14:27 CST 2017
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTACT_INFO.status
     *
     * @mbggenerated Thu Oct 26 10:14:27 CST 2017
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTACT_INFO.create_time
     *
     * @mbggenerated Thu Oct 26 10:14:27 CST 2017
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTACT_INFO.id
     *
     * @return the value of CONTACT_INFO.id
     *
     * @mbggenerated Thu Oct 26 10:14:27 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTACT_INFO.id
     *
     * @param id the value for CONTACT_INFO.id
     *
     * @mbggenerated Thu Oct 26 10:14:27 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTACT_INFO.name
     *
     * @return the value of CONTACT_INFO.name
     *
     * @mbggenerated Thu Oct 26 10:14:27 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTACT_INFO.name
     *
     * @param name the value for CONTACT_INFO.name
     *
     * @mbggenerated Thu Oct 26 10:14:27 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTACT_INFO.email
     *
     * @return the value of CONTACT_INFO.email
     *
     * @mbggenerated Thu Oct 26 10:14:27 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTACT_INFO.email
     *
     * @param email the value for CONTACT_INFO.email
     *
     * @mbggenerated Thu Oct 26 10:14:27 CST 2017
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTACT_INFO.phone
     *
     * @return the value of CONTACT_INFO.phone
     *
     * @mbggenerated Thu Oct 26 10:14:27 CST 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTACT_INFO.phone
     *
     * @param phone the value for CONTACT_INFO.phone
     *
     * @mbggenerated Thu Oct 26 10:14:27 CST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTACT_INFO.content
     *
     * @return the value of CONTACT_INFO.content
     *
     * @mbggenerated Thu Oct 26 10:14:27 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTACT_INFO.content
     *
     * @param content the value for CONTACT_INFO.content
     *
     * @mbggenerated Thu Oct 26 10:14:27 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTACT_INFO.status
     *
     * @return the value of CONTACT_INFO.status
     *
     * @mbggenerated Thu Oct 26 10:14:27 CST 2017
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTACT_INFO.status
     *
     * @param status the value for CONTACT_INFO.status
     *
     * @mbggenerated Thu Oct 26 10:14:27 CST 2017
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTACT_INFO.create_time
     *
     * @return the value of CONTACT_INFO.create_time
     *
     * @mbggenerated Thu Oct 26 10:14:27 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTACT_INFO.create_time
     *
     * @param createTime the value for CONTACT_INFO.create_time
     *
     * @mbggenerated Thu Oct 26 10:14:27 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}