package com.bt.shopguide.dao.entity;

import java.util.Date;

public class Coupon {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUPONS.id
     *
     * @mbggenerated Thu Nov 23 09:52:30 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUPONS.store
     *
     * @mbggenerated Thu Nov 23 09:52:30 CST 2017
     */
    private String store;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUPONS.img_url
     *
     * @mbggenerated Thu Nov 23 09:52:30 CST 2017
     */
    private String imgUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUPONS.code
     *
     * @mbggenerated Thu Nov 23 09:52:30 CST 2017
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUPONS.summary
     *
     * @mbggenerated Thu Nov 23 09:52:30 CST 2017
     */
    private String summary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUPONS.url
     *
     * @mbggenerated Thu Nov 23 09:52:30 CST 2017
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUPONS.expire
     *
     * @mbggenerated Thu Nov 23 09:52:30 CST 2017
     */
    private Date expire;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUPONS.create_time
     *
     * @mbggenerated Thu Nov 23 09:52:30 CST 2017
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUPONS.id
     *
     * @return the value of COUPONS.id
     *
     * @mbggenerated Thu Nov 23 09:52:30 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUPONS.id
     *
     * @param id the value for COUPONS.id
     *
     * @mbggenerated Thu Nov 23 09:52:30 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUPONS.store
     *
     * @return the value of COUPONS.store
     *
     * @mbggenerated Thu Nov 23 09:52:30 CST 2017
     */
    public String getStore() {
        return store;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUPONS.store
     *
     * @param store the value for COUPONS.store
     *
     * @mbggenerated Thu Nov 23 09:52:30 CST 2017
     */
    public void setStore(String store) {
        this.store = store == null ? null : store.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUPONS.img_url
     *
     * @return the value of COUPONS.img_url
     *
     * @mbggenerated Thu Nov 23 09:52:30 CST 2017
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUPONS.img_url
     *
     * @param imgUrl the value for COUPONS.img_url
     *
     * @mbggenerated Thu Nov 23 09:52:30 CST 2017
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUPONS.code
     *
     * @return the value of COUPONS.code
     *
     * @mbggenerated Thu Nov 23 09:52:30 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUPONS.code
     *
     * @param code the value for COUPONS.code
     *
     * @mbggenerated Thu Nov 23 09:52:30 CST 2017
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUPONS.summary
     *
     * @return the value of COUPONS.summary
     *
     * @mbggenerated Thu Nov 23 09:52:30 CST 2017
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUPONS.summary
     *
     * @param summary the value for COUPONS.summary
     *
     * @mbggenerated Thu Nov 23 09:52:30 CST 2017
     */
    public void setSummary(String summary) {
        this.summary = summary == null ? null : summary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUPONS.url
     *
     * @return the value of COUPONS.url
     *
     * @mbggenerated Thu Nov 23 09:52:30 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUPONS.url
     *
     * @param url the value for COUPONS.url
     *
     * @mbggenerated Thu Nov 23 09:52:30 CST 2017
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUPONS.expire
     *
     * @return the value of COUPONS.expire
     *
     * @mbggenerated Thu Nov 23 09:52:30 CST 2017
     */
    public Date getExpire() {
        return expire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUPONS.expire
     *
     * @param expire the value for COUPONS.expire
     *
     * @mbggenerated Thu Nov 23 09:52:30 CST 2017
     */
    public void setExpire(Date expire) {
        this.expire = expire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUPONS.create_time
     *
     * @return the value of COUPONS.create_time
     *
     * @mbggenerated Thu Nov 23 09:52:30 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUPONS.create_time
     *
     * @param createTime the value for COUPONS.create_time
     *
     * @mbggenerated Thu Nov 23 09:52:30 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}