package com.bt.shopguide.dao.entity;

import java.util.Date;

public class UserAction {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERS_ACTIONS.id
     *
     * @mbggenerated Tue Oct 17 17:00:57 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERS_ACTIONS.user_id
     *
     * @mbggenerated Tue Oct 17 17:00:57 CST 2017
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERS_ACTIONS.operate_type
     *
     * @mbggenerated Tue Oct 17 17:00:57 CST 2017
     */
    private Integer operateType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERS_ACTIONS.page_url
     *
     * @mbggenerated Tue Oct 17 17:00:57 CST 2017
     */
    private String pageUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERS_ACTIONS.good_id
     *
     * @mbggenerated Tue Oct 17 17:00:57 CST 2017
     */
    private Long goodId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERS_ACTIONS.keyword
     *
     * @mbggenerated Tue Oct 17 17:00:57 CST 2017
     */
    private String keyword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERS_ACTIONS.operate_time
     *
     * @mbggenerated Tue Oct 17 17:00:57 CST 2017
     */
    private Date operateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERS_ACTIONS.create_time
     *
     * @mbggenerated Tue Oct 17 17:00:57 CST 2017
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERS_ACTIONS.id
     *
     * @return the value of USERS_ACTIONS.id
     *
     * @mbggenerated Tue Oct 17 17:00:57 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERS_ACTIONS.id
     *
     * @param id the value for USERS_ACTIONS.id
     *
     * @mbggenerated Tue Oct 17 17:00:57 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERS_ACTIONS.user_id
     *
     * @return the value of USERS_ACTIONS.user_id
     *
     * @mbggenerated Tue Oct 17 17:00:57 CST 2017
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERS_ACTIONS.user_id
     *
     * @param userId the value for USERS_ACTIONS.user_id
     *
     * @mbggenerated Tue Oct 17 17:00:57 CST 2017
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERS_ACTIONS.operate_type
     *
     * @return the value of USERS_ACTIONS.operate_type
     *
     * @mbggenerated Tue Oct 17 17:00:57 CST 2017
     */
    public Integer getOperateType() {
        return operateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERS_ACTIONS.operate_type
     *
     * @param operateType the value for USERS_ACTIONS.operate_type
     *
     * @mbggenerated Tue Oct 17 17:00:57 CST 2017
     */
    public void setOperateType(Integer operateType) {
        this.operateType = operateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERS_ACTIONS.page_url
     *
     * @return the value of USERS_ACTIONS.page_url
     *
     * @mbggenerated Tue Oct 17 17:00:57 CST 2017
     */
    public String getPageUrl() {
        return pageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERS_ACTIONS.page_url
     *
     * @param pageUrl the value for USERS_ACTIONS.page_url
     *
     * @mbggenerated Tue Oct 17 17:00:57 CST 2017
     */
    public void setPageUrl(String pageUrl) {
        this.pageUrl = pageUrl == null ? null : pageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERS_ACTIONS.good_id
     *
     * @return the value of USERS_ACTIONS.good_id
     *
     * @mbggenerated Tue Oct 17 17:00:57 CST 2017
     */
    public Long getGoodId() {
        return goodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERS_ACTIONS.good_id
     *
     * @param goodId the value for USERS_ACTIONS.good_id
     *
     * @mbggenerated Tue Oct 17 17:00:57 CST 2017
     */
    public void setGoodId(Long goodId) {
        this.goodId = goodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERS_ACTIONS.keyword
     *
     * @return the value of USERS_ACTIONS.keyword
     *
     * @mbggenerated Tue Oct 17 17:00:57 CST 2017
     */
    public String getKeyword() {
        return keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERS_ACTIONS.keyword
     *
     * @param keyword the value for USERS_ACTIONS.keyword
     *
     * @mbggenerated Tue Oct 17 17:00:57 CST 2017
     */
    public void setKeyword(String keyword) {
        this.keyword = keyword == null ? null : keyword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERS_ACTIONS.operate_time
     *
     * @return the value of USERS_ACTIONS.operate_time
     *
     * @mbggenerated Tue Oct 17 17:00:57 CST 2017
     */
    public Date getOperateTime() {
        return operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERS_ACTIONS.operate_time
     *
     * @param operateTime the value for USERS_ACTIONS.operate_time
     *
     * @mbggenerated Tue Oct 17 17:00:57 CST 2017
     */
    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERS_ACTIONS.create_time
     *
     * @return the value of USERS_ACTIONS.create_time
     *
     * @mbggenerated Tue Oct 17 17:00:57 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERS_ACTIONS.create_time
     *
     * @param createTime the value for USERS_ACTIONS.create_time
     *
     * @mbggenerated Tue Oct 17 17:00:57 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}