package com.bt.shopguide.dao.mapper;

import com.bt.shopguide.dao.entity.ContactInfo;

public interface ContactInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONTACT_INFO
     *
     * @mbggenerated Thu Oct 26 10:14:27 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONTACT_INFO
     *
     * @mbggenerated Thu Oct 26 10:14:27 CST 2017
     */
    int insert(ContactInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONTACT_INFO
     *
     * @mbggenerated Thu Oct 26 10:14:27 CST 2017
     */
    int insertSelective(ContactInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONTACT_INFO
     *
     * @mbggenerated Thu Oct 26 10:14:27 CST 2017
     */
    ContactInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONTACT_INFO
     *
     * @mbggenerated Thu Oct 26 10:14:27 CST 2017
     */
    int updateByPrimaryKeySelective(ContactInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONTACT_INFO
     *
     * @mbggenerated Thu Oct 26 10:14:27 CST 2017
     */
    int updateByPrimaryKey(ContactInfo record);
}