package com.bt.shopguide.dao.mapper;

import com.bt.shopguide.dao.entity.UserAction;

public interface UserActionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERS_ACTIONS
     *
     * @mbggenerated Tue Oct 17 17:00:57 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERS_ACTIONS
     *
     * @mbggenerated Tue Oct 17 17:00:57 CST 2017
     */
    int insert(UserAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERS_ACTIONS
     *
     * @mbggenerated Tue Oct 17 17:00:57 CST 2017
     */
    int insertSelective(UserAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERS_ACTIONS
     *
     * @mbggenerated Tue Oct 17 17:00:57 CST 2017
     */
    UserAction selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERS_ACTIONS
     *
     * @mbggenerated Tue Oct 17 17:00:57 CST 2017
     */
    int updateByPrimaryKeySelective(UserAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERS_ACTIONS
     *
     * @mbggenerated Tue Oct 17 17:00:57 CST 2017
     */
    int updateByPrimaryKey(UserAction record);
}